version: '3.5'

services:
  blog-db:
    image: mysql:8.0.22
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3333:3306"
    environment:
       MYSQL_ROOT_PASSWORD: rootroot
       MYSQL_DATABASE: blogdb
       MYSQL_USER: mysql
       MYSQL_PASSWORD: pass

volumes:
  db_data: